[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GNSSSignals = "52c80523-2a4e-5c38-8979-05588f836870"
Tracking = "10b2438b-ffd4-5096-aa58-44041d5c8f3b"
TrackingLoopFilters = "0814aff9-93cb-554c-9fff-9bf1cfdb5efa"

[compat]
Documenter = "1"
